apiVersion: 1

contactPoints:
  - orgId: 1
    name: frontend-discord
    receivers:
      - uid: frontend_discord
        type: discord
        disableResolveMessage: false
        settings:
          url: $GRAFANA_ALERTS_DISCORD_WEBHOOK_URL
          use_discord_username: false
          message: |
            {{ template "default.message" . }}
