apiVersion: 1

contactPoints:
  - orgId: 1
    name: frontend-discord
    receivers:
      - uid: frontend_discord
        type: discord
        disableResolveMessage: false
        settings:
          url: $GRAFANA_ALERTS_DISCORD_WEBHOOK_URL
          use_discord_username: false
          message: |
            {{ template "default.message" . }}
  - orgId: 1
    name: frontend-analyzer
    receivers:
      - uid: frontend_analyzer
        type: webhook
        disableResolveMessage: true
        settings:
          url: $GRAFANA_ALERTS_ANALYZER_WEBHOOK_URL
          httpMethod: POST
          maxAlerts: "10"
