apiVersion: 1

policies:
  - orgId: 1
    receiver: frontend-discord
    group_by:
      - alertname
      - route
    group_wait: 10s
    group_interval: 30s
    repeat_interval: 1h
    routes:
      - receiver: frontend-analyzer
        object_matchers:
          - ["team", "=", "frontend-observability"]
          - ["severity", "=", "error"]
      - receiver: frontend-discord
        object_matchers:
          - ["team", "=", "frontend-observability"]
